# Site settings
title: Highlights
email: youremailaddress@gmail.com
description: The Jekyll version of the Highlights theme by HTML5 UP.
baseurl: "/thekings" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
